//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDetailsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserDetail
    {
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserFullName { get; set; }
        public string UserAddress { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserPhoto { get; set; }
        public Nullable<int> UserPhotoId { get; set; }
        public string UserAdharCardNo { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UniqId { get; set; }
    }
}
